### ISSUE TITLE
Instantiating a GameObject with a MonoBehaviour attached causes exception

### ISSUE THREAD

**Issue by Lr-K** [scottyboy805/dotnow-interpreter#16]
Given the existing code to load a MonoBehaviour and attach it to a GameObject
```
var gameObject = new GameObject("original");
AppDomain domain = new AppDomain();

// Load the module
CLRModule module = domain.LoadModuleStream(new MemoryStream(assemblyModule.bytes), false);

// Find the main type
Type mainType = module.GetTypes()
    .Where(t => t.IsSubclassOf(typeof(MonoBehaviour)))
    .FirstOrDefault();

// Add component - cannot use 'gameObject.AddComponent' because it would crash the engine.
MonoBehaviourProxy.AddComponentOverride(domain, null, gameObject, new object[] { mainType });
```

The following code, which is the mainType in the code above, does not work

```
using UnityEngine;

namespace InstantiateMonobehaviourTest
{
    public class TestCase : MonoBehaviour
    {
        public void Start()
        {
            Instantiate(gameObject);
        }
    }
}
```

One GameObject "original" will be created with the correct MonoBehaviour. Once Start() is called, an exception will occur

**Comment by scottyboy805** [comment]
[8b14420](https://github.com/scottyboy805/dotnow-interpreter/commit/8b14420a8c754f52fcec06a5a49b70fb25df1797) adds initial support for using instantiate with interpreted scripts. May need revisions in the future and does not support all cases at the moment like instantiating a disabled game object, but the above sample is now working as intended so I will close for now.
