### ISSUE TITLE
Generics remain null after declaration/assignment

### ISSUE THREAD

**Issue by casefc3s** [scottyboy805/dotnow-interpreter#19]
Error: `Failed to compile/create instance: System.TypeLoadException: Type context must be provided when resolving a generic argument type`

Example scripted method being called with above issue present: 
```
        public void RunRefTypes(int iterations)
        {
            var myList = new ListPlaceholder();
            for (int i = 0; i < 5; ++i)
            {
                myList.Add(i);
            }
            myList.Remove(2);
            myList.AddRange(new int[] {5, 6, 7});
            Debug.Log($"List<int>: {myList}");
            
            var dict = new DictPlaceholder
            {
                { "hello", 42 }
            };
            dict.Add("world", 123);
            dict["test"] = 789;
            dict.Remove("test");
            if (dict.ContainsKey("test"))
            {
                Debug.LogError("Dictionary still contained removed key");
            }
            Debug.Log($"dict[hello]: {dict["hello"]}, dict[world]: {dict["world"]}");
            
            var sb = new StringBuilder();
            sb.Append("hello");
            sb.AppendLine(" world!");
            Debug.Log(sb.ToString());
        }
```

All of the variables above will throw a null ref exception after declaration. ListPlaceholder is just an empty class that inherits from List<int>, similarly for DictPlaceholder, was experimenting with potential workarounds. Sent over repro project, just tracking the issue here, let me know if more details are required!

**Comment by scottyboy805** [comment]
After some more investigation it looks like the issue was not a major issue after all. It is now fixed in [044024e](https://github.com/scottyboy805/dotnow-interpreter/commit/044024ef8b6b8e60a421c4cff6d20fb6075e145a)
