### ISSUE TITLE
Try/catch in runtime script methods

### ISSUE THREAD

**Issue by will-aristocrat** [scottyboy805/dotnow-interpreter#22]
When using a try/catch block inside a runtime script it will not pass through into the catch due to the CLRExceptionHandler injecting its own try/catch at the first/last lines of a method.

**Comment by scottyboy805** [comment]
Fixed in [5d0c9a4](https://github.com/scottyboy805/dotnow-interpreter/commit/5d0c9a4e4c620d19917220c3c4db23a6bda4e9d1)
