### ISSUE TITLE
Using outside of Unity?

### ISSUE THREAD

**Issue by KUNGERMOoN** [scottyboy805/dotnow-interpreter#25]
Edit: I forgot the description says it's pure C# project, which answers the first part of the question

Hi, does this project use any Unity-specific code, or can it be used in any C# project?

And if yes, can I use it with C# to native compiler other than IL2CPP, like Brute (similar to IL2CPP, used by MonoGame to compile C# to C++ for consoles) or NativeAOT? (the new, official Microsoft's IL to native code compiler)
([This](https://viridiansoftware.com/blog/csharp-on-game-consoles) article explains the current situation with C# to native code compilation)

**Comment by scottyboy805** [comment]
Hey, dotnow is indeed designed to run independant of any game engine, although there are Unity specific modules (add-ons) and the repo structure is geard towards Unity specifically (Using Unity project structure, Asmdefs, etc.)
The core can be used by from any C# project or engine so I see no issues in using it with MonoGame or NativeAOT. Only main issue is that releases are distributed as .unitypackage, but if you clone the repo you should be fine.
Feel free to open any more issues if you have specific problems and i wil be happy to check it out.
