### ISSUE TITLE
Android: FileNotFoundException: Could not find file "/mscorlib.dll"

### ISSUE THREAD

**Issue by styrbo** [scottyboy805/dotnow-interpreter#4]
How to reproduce:
1) download last release [version 0.0.9-beta](https://github.com/scottyboy805/dotnow-interpreter/releases/tag/v0.0.9-beta)
2) Change platform to Android, set .net version to 4.x and add ARM64 in Target Architectures
3) Build Snake example scene

This Exception canceled loading assembly

**Comment by scottyboy805** [comment]
Fixed in [b9c3879](https://github.com/scottyboy805/dotnow-interpreter/commit/b9c3879066c55b803c23818cff93821399ef60c5). I could not find a workaround for the moment so deferred mode will have to stay until it becomes an issue.
